apiVersion: v1  
kind: Service  
metadata:  
  name: uiweb  
  namespace: microservices-app  
  labels:  
    app: uiweb  
    tier: frontend  
spec:  
  type: LoadBalancer  
  selector:  
    app: uiweb  
  ports:  
  - name: http  
    protocol: TCP  
    port: 3000  
    targetPort: http  
